refactor: use ruff as the server
sublimelsp/LSP-ruff pull request #58
Opened 2024-04-19 02:46 UTC by jfcherng

As of ruff 0.4.0, it can be used as a LSP server.
We no longer need the ruff-lsp wrapper and ruff itself as a server is even faster.

ref: https://github.com/astral-sh/ruff/releases/tag/v0.4.0

2024-04-19 02:51 UTC, jfcherng commented
Technically, we no longer need to have Python installed on the machine now. We need it before because `ruff-lsp` is written in Python. 

`ruff` itself can be downloaded from GitHub release. That means `LSP-ruff` doesn't have to inherit `PipClientHandler`.

2024-04-19 07:12 UTC, rchl commented
The changelog says that it's in alpha which makes me want to wait with switching to it since there might be potentially missing features or bugs to iron out.

2024-04-19 07:19 UTC, rchl commented
BTW. We have github actions that can monitor github releases (used in LSP-rust-analyzer for example)

2024-04-19 07:21 UTC, jfcherng commented
> BTW. We have github actions that can monitor github releases (used in LSP-rust-analyzer for example)

Thanks for the info. I am pretty sure that is what I was looking for repositories I forgot...

2024-04-19 08:02 UTC, LDAP commented
I have one for LSP-clangd too https://github.com/sublimelsp/LSP-clangd/blob/main/.github/workflows/update_check.yaml

2024-07-18 17:33 UTC, jfcherng commented
https://github.com/astral-sh/ruff/releases/tag/0.5.3

Ruff 0.5.3 marks the stable release of the Ruff language server and introduces revamped [documentation](https://docs.astral.sh/ruff/editors), including [setup guides for your editor of choice](https://docs.astral.sh/ruff/editors/setup) and [the language server itself](https://docs.astral.sh/ruff/editors/settings).

2024-07-22 08:33 UTC, rchl approved these changes

2024-07-22 08:37 UTC, rchl requested changes
I saw now that there are some setting changes: https://docs.astral.sh/ruff/editors/migration/

Will you handle that or do you want someone to take over?

2024-07-22 12:06 UTC, jfcherng commented
> I saw now that there are some setting changes: [docs.astral.sh/ruff/editors/migration](https://docs.astral.sh/ruff/editors/migration/)
> 
> Will you handle that or do you want someone to take over?

done

2024-07-22 12:40 UTC, rchl approved these changes

2024-07-22 12:41 UTC, rchl commented on LSP-ruff.sublime-settings
> +            // The strategy to use when resolving settings across VS Code and the filesystem. By default, editor configuration is prioritized over ruff.toml and pyproject.toml files.
```suggestion
            // The strategy to use when resolving settings across editor and the filesystem. By default, editor configuration is prioritized over ruff.toml and pyproject.toml files.
```

2024-07-22 12:41 UTC, rchl commented on sublime-package.json
> +                  "markdownDescription": "The strategy to use when resolving settings across VS Code and the filesystem. By default, editor configuration is prioritized over `ruff.toml` and `pyprojec
```suggestion
                  "markdownDescription": "The strategy to use when resolving settings across editor and the filesystem. By default, editor configuration is prioritized over `ruff.toml` and `pyproject.toml` files."
```

2024-07-22 14:42 UTC, rchl approved these changes

2024-07-22 14:46 UTC, merged